# This is a sample analysis template that uses the PokeAPI to
# check the base experience of a Pokemon is under threshold.
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: pokemon-xp
  namespace: kargo-advanced
spec:
  args:
  - name: pokemon
  metrics:
  - name: pokemon-xp
    interval: 5s
    count: 5
    successCondition: result < 200
    failureLimit: 3
    provider:
      job:
        spec:
          template:
            spec:
              containers:
              - name: verification-container
                image: busybox:latest
                command:
                - sh
                - -c
                - |
                  # All echo statements output to stdout/stderr for log collection
                  echo "=== Verification Starting ===" >&2
                  echo "Checking Pokemon: {{args.pokemon}}" >&2
                  echo "Fetching data..." >&2
                  
                  # Simulate a check - set the result value
                  # In real usage, this would be your actual verification logic
                  XP=112
                  
                  # Log the result to stderr (for viewing in Kargo UI/CLI)
                  echo "Result: $XP" >&2
                  echo "=== Verification Complete ===" >&2
                  
                  # CRITICAL: Output ONLY the numeric result to stdout (last line)
                  # Argo Rollouts reads the last line of stdout as the result value
                  # No text, no labels, just the number
                  printf "%d\n" $XP
              restartPolicy: Never
